name: Bump Version
on:
  workflow_dispatch:
    inputs:
       version:
         description: Bump Version
         default: 1.0.0-SNAPSHOT
         required: true    

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Update to latest parent version
        run: mvn -f ./src/pom.xml versions:update-parent -DallowSnapshots=true -DparentVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
      - name: Update child modules
        run: mvn -f ./src/pom.xml versions:update-child-modules -N -DallowSnapshots=true -DgenerateBackupPoms=false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.3.0
        with:
          token: ${{ secrets.GH_TOKEN_PAT }}
          commit-message: "Bump version to ${{ github.event.inputs.version }}"
          committer: AutoBumper <autobumper@autobumper>
          author: AutoBumper <autobumper@autobumper>
          branch: "bump-${{ github.event.inputs.version }}"
          title: "Bump to version ${{ github.event.inputs.version }}"
          body: ""
          
